Repository ForYouTeam/SEPON, pull requests merged in 2022-07, with the labels that each got.

#3 Model
  app/Http/Requests/DetailDuaRequest.php
  app/Http/Requests/DetailSatuRequest.php
  app/Http/Requests/FasilitasRequest.php
  app/Http/Requests/GaleriRequest.php
  app/Http/Requests/GuruRequest.php
  app/Http/Requests/PendaftaranRequest.php
  app/Http/Requests/ProfilRequest.php
  app/Http/Requests/SiswaRequest.php
  app/Http/Requests/WaliMuridRequest.php
  app/Models/DetailDuaModel.php
  app/Models/DetailSatuModel.php
  app/Models/FasilitasModel.php
  app/Models/GaleriModel.php
  app/Models/GuruModel.php
  app/Models/PendaftaranModel.php
  app/Models/ProfilModel.php
  app/Models/SiswaModel.php
  app/Models/WaliMuridModel.php
  database/migrations/2022_07_17_151827_create_wali_murid_table.php
  routes/web.php
Labels: development

#4 Remove: Button upgrade pro
  public/cms/assets/js/pcoded.min.js
  resources/views/cms/layout/TemplateAdmin.blade.php
Labels: development

#5 modified request
  app/Http/Requests/DetailDuaRequest.php
  app/Http/Requests/DetailSatuRequest.php
  app/Http/Requests/FasilitasRequest.php
  app/Http/Requests/GaleriRequest.php
  app/Http/Requests/GuruRequest.php
  app/Http/Requests/PendaftaranRequest.php
  app/Http/Requests/ProfilRequest.php
  app/Http/Requests/SiswaRequest.php
  app/Http/Requests/WaliMuridRequest.php
  resources/views/cms/layout/TemplateAdmin.blade.php
Labels: development

#6 Se 01
  app/Http/Controllers/cms/SiswaController.php
  resources/views/cms/layout/Navbar.blade.php
  resources/views/cms/layout/TemplateAdmin.blade.php
  resources/views/cms/page/Siswa.blade.php
  routes/web.php
Labels: development

#7 Wali murid
  app/Http/Controllers/cms/WaliMuridController.php
  app/Http/Requests/WaliMuridRequest.php
  app/Models/WaliMuridModel.php
  database/migrations/2022_07_17_151827_create_wali_murid_table.php
  resources/lang/id/auth.php
  resources/lang/id/pagination.php
  resources/lang/id/passwords.php
  resources/lang/id/validation.php
  resources/views/cms/layout/TemplateAdmin.blade.php
  resources/views/cms/page/WaliMurid.blade.php
  routes/web.php
Labels: development

#8 Done: Tabel pendaftar
  app/Http/Controllers/cms/PendaftranController.php
  app/Http/Controllers/cms/WaliMuridController.php
  app/Http/Requests/PendaftaranRequest.php
  app/Models/PendaftaranModel.php
  database/migrations/2022_07_17_151034_create_pendaftaran_table.php
  database/migrations/2022_07_17_151812_create_detail_1_table.php
  public/cms/assets/css/yearpicker.css
  public/cms/assets/js/yearpicker.js
  resources/views/cms/layout/TemplateAdmin.blade.php
  resources/views/cms/page/Pendaftar.blade.php
  routes/web.php
Labels: development

#11 Fix conflict
  app/Http/Controllers/cms/GuruController.php
  resources/views/cms/page/Guru.blade.php
  routes/web.php
Labels: bug

#12 Se 04.1
  app/Http/Controllers/cms/GaleriController.php
  app/Http/Requests/GaleriRequest.php
  app/Http/Requests/GuruRequest.php
  resources/views/cms/layout/Navbar.blade.php
  resources/views/cms/page/Galeri.blade.php
  routes/web.php
Labels: development

#14 Se 06
  app/Http/Controllers/cms/DashboardController.php
  resources/views/cms/layout/Navbar.blade.php
  resources/views/cms/page/Dashboard.blade.php
  routes/web.php
Labels: development

#16 Auth route done
  routes/web.php
Labels: development

#17 User 01
  app/Http/Controllers/cms/DashboardController.php
  app/Http/Requests/ProfilRequest.php
  database/migrations/2022_07_17_151301_create_profile_sekolah_table.php
  resources/views/cms/layout/Navbar.blade.php
  resources/views/cms/page/Dashboard.blade.php
  routes/web.php
Labels: development

#18 User pendaftaran
  app/Http/Controllers/auth/AuthController.php
  app/Http/Controllers/cms/DashboardController.php
  app/Http/Controllers/web/PendaftaranSiswaController.php
  app/Http/Requests/WaliMuridRequest.php
  app/Http/Requests/WebPendaftaranRequest.php
  app/Models/DetailSatuModel.php
  app/Repositories/DetailRepository.php
  database/migrations/2022_07_18_151812_create_detail_1_table.php
  resources/views/auth/Login.blade.php
  resources/views/auth/Register.blade.php
  resources/views/cms/layout/Navbar.blade.php
  resources/views/cms/layout/TemplateAdmin.blade.php
  resources/views/cms/page/Dashboard.blade.php
  resources/views/cms/page/Galeri.blade.php
  resources/views/cms/page/Pendaftar.blade.php
  resources/views/cms/page/WaliMurid.blade.php
  resources/views/web/layout/FormPendaftaran.blade.php
  resources/views/web/layout/TableDataPendaftar.blade.php
  resources/views/web/page/PendaftaranSiswa.blade.php
  routes/web.php
Labels: bug, development

#19 User 02
  app/Http/Controllers/auth/AuthController.php
  app/Http/Controllers/web/UserDashController.php
  resources/views/cms/page/Dashboard.blade.php
  resources/views/cms/page/Guru.blade.php
  resources/views/web/layout/userweb.blade.php
  routes/web.php
Labels: development
